#%RAML 1.0
title: Order API
version: v1
baseUri: https://api.example.com/v1

/orders:
  get:
    description: Get a list of orders
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "resource": "order",
                  "id": "ord_kEn1PlbGa",
                  "profileId": "pfl_URR55HPMGx",
                  "method": "ideal",
                  "amount": {
                    "value": "1027.99",
                    "currency": "EUR"
                  },
                  "status": "created",
                  "isCancelable": true,
                  "metadata": null,
                  "createdAt": "2018-08-02T09:29:56+00:00",
                  "expiresAt": "2018-08-30T09:29:56+00:00",
                  "mode": "live",
                  "locale": "nl_NL",
                  "billingAddress": {
                    "organizationName": "Mollie B.V.",
                    "streetAndNumber": "Keizersgracht 126",
                    "postalCode": "1015 CW",
                    "city": "Amsterdam",
                    "country": "nl",
                    "givenName": "Luke",
                    "familyName": "Skywalker",
                    "email": "luke@skywalker.com"
                  },
                  "shopperCountryMustMatchBillingCountry": false,
                  "consumerDateOfBirth": "1993-10-21",
                  "orderNumber": "18475",
                  "shippingAddress": {
                    "organizationName": "Mollie B.V.",
                    "streetAndNumber": "Keizersgracht 126",
                    "postalCode": "1015 CW",
                    "city": "Amsterdam",
                    "country": "nl",
                    "givenName": "Luke",
                    "familyName": "Skywalker",
                    "email": "luke@skywalker.com"
                  }
                }
              ]
